language: java
addons: 
 sonarcloud:
    organization: "oxygenxml-github"
    token:
      secure: "${SONAR_CLOUD_TOKEN}"
script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
